### ISSUE TITLE
request(commits): use lua fivem lint action 

### ISSUE THREAD

**Issue by TheSpaceGamerV2** [NextCitizens/ncs_core#2]
Would be good to use this <a href="https://github.com/GoatG33k/fivem-lua-lint-action">bot</a> for the commits

**Comment by ZAKIO59** [comment]
This linter support backticks.
https://github.com/iLLeniumStudios/fivem-lua-lint-action

**Comment by PABLO-1610** [comment]
> This linter support backticks. https://github.com/iLLeniumStudios/fivem-lua-lint-action

Thx, added into the repo 😁
