### ISSUE TITLE
HUD in the core ?

### ISSUE THREAD

**Issue by PABLO-1610** [NextCitizens/ncs_core#46]
I propose to do the design part with React or Preact and then integrate the HUD later.

_Originally posted by @MoskalykA in https://github.com/NextCitizens/ncs_core/issues/30#issuecomment-1139916333_

**Comment by PABLO-1610** [comment]
We can discuss about the HUD here

**Comment by MoskalykA** [comment]
I propose to put a basic HUD once the design system is finished.

**Comment by PABLO-1610** [comment]
A hud has been set.
