### ISSUE TITLE
:bug:  Unlimited Pistol Ammo

### ISSUE THREAD

**Issue by Tarkiom** [NextCitizens/ncs_core#94]
**Describe the bug**
> Hello I noticed when giving me a pistol (any type of pistol) that even if I put that I want 15  bullet the bullet bug and becomes unlimited

**To Reproduce**
> Juste give you any type of  pistol 

**Screenshots**
> https://gyazo.com/a4c989ed39d27279ac4c949e221d44d9 /  https://gyazo.com/40043c82fe75d8fa49f59dac35485b00

**Comment by Zeleeer** [comment]
Hi, i have try but i haven't problem with appistol and pistol 

![image](https://user-images.githubusercontent.com/106283602/171021079-b9f0f0bb-d8dc-4dcd-864d-5979c0de5c3a.png)

**Comment by Tarkiom** [comment]
Hum, Do you give you like me ?

**Comment by Tarkiom** [comment]
Ok I tested and now it works without worries I must have had a weird bug on my side!
